### ISSUE TITLE
Can't resolve defu in @vueuse/motion/dist/index.mjs

### ISSUE THREAD

**Issue by mikael-j-rich** [vueuse/motion#166] opened 2024-01-12 14:16 UTC
The dependency "defu" does not seem to get installed. Where is this coming from?

**Comment by wuhaohuang** [comment] 2024-01-15 10:25
same problem + 1

**Comment by aquarius-wing** [comment] 2024-02-03 09:22
I solved it by execute the shell below
```
npm install defu
```
or
```
yarn add defu
```

**Comment by BobbieGoede** [comment] 2024-02-23 15:16
I'm unable to reproduce this using the latest release so I'm closing this, if you're still experiencing this after updating please open a new issue with a reproduction.

**Closed by BobbieGoede** 2024-02-23 15:16 UTC

**Comment by NoelDeMartin** [comment] 2024-12-30 08:59
@BobbieGoede I'm facing this issue as well, but I don't have a minimal example that I can share.

Before trying to have a minimal example, though, I wonder why `defu` is not declared as a dependency in the package.json? It [seems to be used](https://github.com/vueuse/motion/blob/main/src/directive/index.ts#L2) in the main functionality, so if this isn't happening in some project it must be because another dependency happens to use it as well.

PS: In case you want the "non minimal" example, it's this repo: https://github.com/noeldemartin/umai

**Comment by jerrybendy** [comment] 2025-08-25 03:12
Same issue to me. I use v2 in my project. There is `defu` as dependency but not in `package.json`. I noticed that the latest version has `defu` in `package.json`, it's better to add it in v2 too.
