### ISSUE TITLE
Nuxt3 composables are not auto imported across all vueuse/motion APIs

### ISSUE THREAD

**Issue by mendrinos** [vueuse/motion#87] opened 2022-10-04 03:51 UTC
<img width="856" alt="Screenshot 2022-10-04 at 11 50 46 AM" src="https://user-images.githubusercontent.com/1592441/193730440-a9140a04-c92b-4987-84a6-62d59e039c27.png">

**Comment by Redemption198** [comment] 2022-10-04 12:16
Original comment in https://github.com/vueuse/motion/issues/86#issuecomment-1263512800

I tested the composables declared [here](https://github.com/vueuse/motion/blob/feat/v2/src/nuxt/runtime/composables/index.ts):

- `reactiveStyle` Not found
- `reactiveTransform` Not found
- `useElementStyle` Ok
- `useElementTransform` Ok
- `useMotion` Ok
- `useMotionControls` Not found
- `useMotionProperties` Ok
- `useMotions`  Not found
- `useMotionTransitions` Not found
- `useMotionVariants` Ok
- `useSpring` Ok
- `useReducedMotion` Not found

**Comment by mendrinos** [comment] 2022-10-10 09:57
@antfu would this be a quick fix? it's totally blocking me from using vueuse/motion under NuxtJS.

**Comment by BobbieGoede** [comment] 2024-02-22 23:59
I'm unable to reproduce this using the latest versions of Nuxt and @vueuse/motion (I know this issue is old). Seems like this can be closed as the issue has been resolved. (same for #86)

**Closed** 2024-02-23 07:49 UTC
