### ISSUE TITLE
Main Entrypoint not recognized as a valid entrypoint

### ISSUE THREAD

**Issue by leonardotessaroalves** [vueuse/motion#39] opened 2021-11-03 12:40 UTC
`Error
Cannot find module '@vueuse/motion/dist/index.js'. Please verify that the package.json has a valid "main" entry`

In package.json
"main": "./index.js" >>> "main": "./index.cjs"

**Comment by Tahul** [comment] 2022-03-15 23:49
I cannot reproduce this issue.

I'm closing this as there is no reproduction, feel free to reopen.

**Closed by Tahul** 2022-03-15 23:49 UTC
