### ISSUE TITLE
TypeScript Errors thrown upon leave transition

### ISSUE THREAD

**Issue by pachiraDIG** [vueuse/motion#13] opened 2021-03-19 04:06 UTC
I'm having a series of errors being thrown in Nuxt 2.15.3 when using a leave transition just like the example [here](https://github.com/vueuse/motion/blob/bf04bd4f4c66409e91e7392099a6ddd6988554c5/demo/src/demos/Transitions.vue) (without importing and using `useToggle`)

 ```
ERROR  ERROR in /Users/brendan/dev/bee/web/node_modules/@vueuse/core/dist/index.d.ts(685,17):
685:17 Cannot find name 'GeolocationCoordinates'.
    683 | declare function useGeolocation(options?: GeolocationOptions): {
    684 |     isSupported: boolean | undefined;
  > 685 |     coords: Ref<GeolocationCoordinates>;
        |                 ^
    686 |     locatedAt: Ref<number | null>;
    687 |     error: Ref<{
    688 |         readonly code: number;
 ```

...

 ```
 ERROR  ERROR in /Users/brendan/dev/bee/web/node_modules/@vueuse/core/dist/index.d.ts(1414,16):
1414:16 Cannot find name 'SpeechRecognitionErrorEvent'.
    1412 |     recognition: SpeechRecognition | undefined;
    1413 |     result: Ref<string>;
  > 1414 |     error: Ref<SpeechRecognitionErrorEvent | undefined>;
         |                ^
    1415 |     toggle: (value?: boolean) => void;
    1416 |     start: () => void;
    1417 |     stop: () => void;
 ```

...

 ```
 ERROR  ERROR in /Users/brendan/dev/bee/web/node_modules/@vueuse/motion/dist/index.d.ts(6,10):
6:10 Module '"../../../vue-demi/lib"' has no exported member 'CSSProperties'.
    4 |   * @license MIT
    5 |   */
  > 6 | import { CSSProperties, SVGAttributes, Ref, UnwrapRef, Directive, Plugin, ComputedRef } from 'vue-demi';
      |          ^
    9 | import { MaybeRef as MaybeRef$1 } from '@vueuse/shared';
 ```

...

 ```
 ERROR  ERROR in /Users/brendan/dev/bee/web/node_modules/@vueuse/motion/dist/index.d.ts(6,25):
6:25 Module '"../../../vue-demi/lib"' has no exported member 'SVGAttributes'.
    4 |   * @license MIT
    5 |   */
  > 6 | import { CSSProperties, SVGAttributes, Ref, UnwrapRef, Directive, Plugin, ComputedRef } from 'vue-demi';
      |                         ^
 ```

...

 ```
 ERROR  ERROR in /Users/brendan/dev/bee/web/node_modules/@vueuse/motion/dist/index.d.ts(6,56):
6:56 Module '"../../../vue-demi/lib"' has no exported member 'Directive'. Did you mean 'isReactive'?
    4 |   * @license MIT
    5 |   */
  > 6 | import { CSSProperties, SVGAttributes, Ref, UnwrapRef, Directive, Plugin, ComputedRef } from 'vue-demi';
      |                          
 ```
...

 ```
 ERROR  ERROR in /Users/brendan/dev/bee/web/node_modules/@vueuse/motion/dist/index.d.ts(6,67):
6:67 Module '"../../../vue-demi/lib"' has no exported member 'Plugin'.
    4 |   * @license MIT
    5 |   */
  > 6 | import { CSSProperties, SVGAttributes, Ref, UnwrapRef, Directive, Plugin, ComputedRef } from 'vue-demi';
      |                                                                   ^
 ```
...

 ```
 ERROR  ERROR in /Users/brendan/dev/bee/web/node_modules/@vueuse/motion/dist/index.d.ts(8,8214):
8:8214 Cannot find module 'csstype' or its corresponding type declarations.
```

**Comment by Tahul** [comment] 2021-03-19 15:21
Hello @pachiraDIG ;

Could you send me a reproduction link please ?

I'm currently using this package on a Nuxt 2.15 project and it is working well. 🤔

**Comment by pachiraDIG** [comment] 2021-03-19 20:21
Hi @Tahul, and thanks for the reply. I was able to reproduce the errors in a code sandbox, [here](https://codesandbox.io/s/wonderful-northcutt-df02x?file=/components/FormButton1.vue).

**Comment by Tahul** [comment] 2021-03-19 20:36
Thanks, I'll take a look at it soon!

**Comment by Tahul** [comment] 2021-03-19 22:27
Hey @pachiraDIG ;

I did get your example to work just fine, you can take a look at it here:
https://codesandbox.io/s/serene-drake-0y49s

Your typing problem is still alarming but it feels like it belongs to the fact that you used useMotions from `data` itself, which is not the usage I recommend.

This should be documented better though.

I'll be updating all the dependencies on the package an publishing another version soon.

Please let me know if you still struggle with this problem in your app, will be glad to help you out again. 😄 

Could you close this issue once the problem is resolved on your side ?

Thanks 👋

**Comment by pachiraDIG** [comment] 2021-03-22 22:55
Hi @Tahul. Thanks again for your help. 😀

Something I forgot to clarify is that the typescript errors are my biggest problem, as I can't pass validation upon merging to our codebase with these errors persisting. Do you have any suggestions in terms of how that FormButton1 component is put together to be able to solve the typescript errors, specifically?

I noticed your change of using the composition api in a way that allows `useMotions` to be used in the template without it becoming reactive. Thanks! Am I understanding that correctly?

**Comment by pachiraDIG** [comment] 2021-03-23 20:23
Solved [here](https://github.com/vueuse/vueuse/issues/231) 🎉

**Closed** 2021-03-23 20:23 UTC
