### ISSUE TITLE
Issues with 2.0.0-beta.1

### ISSUE THREAD

**Issue by HassanZahirnia** [vueuse/motion#31] opened 2021-09-09 09:59 UTC
Hey,
I recently found out about this package and decided to give a try and unfortunately I kept getting 3 different `Module not found` errors. At first I thought it's a compatibility issue with vue 2 since I use that and I almost gave up.

I decided to try the previous release (`1.6.0`) and now it's working just fine!

I just wanted to let you know of the issue.

Thanks a lot and have a great day!

**Comment by Tahul** [comment] 2021-11-03 01:35
Hello xperator 😄

Have you tried latest beta versions?

2.0.0-beta.4 and above should solve your problem. 😄

**Comment by apuatcfbd** [comment] 2021-11-18 15:50
Just after installation, packages should be QA tested at least on a minimum level

![image](https://user-images.githubusercontent.com/74357797/142448924-f9da953e-2a49-47d1-9a9b-82caf80b6910.png)

**Comment by Tahul** [comment] 2022-03-15 23:55
Hello,

Could you provide a reproduction?

I'm closing this as it is pretty old and can't reproduce it myself.

Feel free to reopen :)

**Closed by Tahul** 2022-03-15 23:55 UTC
