### ISSUE TITLE
Installing with npm and vue3

### ISSUE THREAD

**Issue by holtwick** [vueuse/motion#3] opened 2021-02-22 15:50 UTC
When installing using `npm` I end up like this:

```
$ npm i @vueuse/motion     
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: twindy-demo@0.3.0
npm ERR! Found: vue@3.0.5
npm ERR! node_modules/vue
npm ERR!   vue@"^3.0.5" from the root project
npm ERR!   peer vue@"^2.0.0 || >=3.0.0-rc.0" from @vueuse/motion@1.0.0
npm ERR!   node_modules/@vueuse/motion
npm ERR!     @vueuse/motion@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 3" from @vue/composition-api@1.0.0-rc.2
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@">=1.0.0-rc.1" from @vueuse/motion@1.0.0
npm ERR!   node_modules/@vueuse/motion
npm ERR!     @vueuse/motion@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/dirk/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dirk/.npm/_logs/2021-02-22T15_35_15_422Z-debug.log
```

My projects dependencies are:

```json
"dependencies": {
    "twindy": "^0.11.0",
    "twindy-headless": "^0.8.0",
    "vue": "^3.0.5",
    "vue-i18n": "^9.0.0-rc.7",
    "vue-router": "^4.0.3"
  },
  "devDependencies": {
    "@types/node": "^14.14.31",
    "@vitejs/plugin-legacy": "^1.3.1",
    "@vitejs/plugin-vue": "^1.1.4",
    "@vue/compiler-sfc": "^3.0.5",
    "@vuedx/typecheck": "^0.6.3",
    "@vuedx/typescript-plugin-vue": "^0.6.3",
    "markdown-it-anchor": "^7.0.2",
    "markdown-it-prism": "^2.1.4",
    "stylus": "^0.54.8",
    "typescript": "^4.1.5",
    "vite": "^2.0.1",
    "vite-plugin-md": "^0.5.1",
    "vite-plugin-pwa": "^0.5.3"
  }
```

Maybe a `npm` issue due to conditions like `"^2.0.0 || >=3.0.0-rc.0"`?

**Comment by santicros** [comment] 2021-02-22 16:02
Hi!!

I'm having the same problem as @holtwick in a fresh project with Vue3 + Vite!

``` sh
$ npm i @vueuse/motion 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue-motion@0.0.0
npm ERR! Found: vue@3.0.5
npm ERR! node_modules/vue
npm ERR!   vue@"^3.0.5" from the root project
npm ERR!   peer vue@"^2.0.0 || >=3.0.0-rc.0" from @vueuse/motion@1.0.1
npm ERR!   node_modules/@vueuse/motion
npm ERR!     @vueuse/motion@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 3" from @vue/composition-api@1.0.0-rc.2
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@">=1.0.0-rc.1" from @vueuse/motion@1.0.1
npm ERR!   node_modules/@vueuse/motion
npm ERR!     @vueuse/motion@"*" from the root project
```

**Comment by holtwick** [comment] 2021-02-22 16:05
A temporary workaround is:

```
npm i @vueuse/motion --legacy-peer-deps
```

But it will fail on updates then.

**Comment by Tahul** [comment] 2021-02-22 22:17
Hey 👋 

I've noticed your issue and pushed an fix, I just tried creating a Vue 3 app w/ Vite and it worked well.

I'll close the issue for now, if you encounter the problem again feel free to re-open it.

**Closed by Tahul** 2021-02-22 22:17 UTC

**Comment by garrlker** [comment] 2021-02-24 01:58
@Tahul  Fwiw I just hit this same issue with the current latest version of vueuse/motion (1.0.5).
Not sure if you've already pushed the fix up or not...

**Comment by santicros** [comment] 2021-02-26 20:00
@Tahul I've checked with latest version 1.1.3 and a fresh Vite 2 + Vue 3 install and this is not working still.

``` sh
npm i @vueuse/motion                          6s
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: vue@3.0.6
npm ERR! node_modules/vue
npm ERR!   peer vue@"3.0.6" from @vue/compiler-sfc@3.0.6
npm ERR!   node_modules/@vue/compiler-sfc
npm ERR!     peer @vue/compiler-sfc@"^3.0.6" from @vitejs/plugin-vue@1.1.5
npm ERR!     node_modules/@vitejs/plugin-vue
npm ERR!       dev @vitejs/plugin-vue@"^1.1.4" from the root project
npm ERR!     dev @vue/compiler-sfc@"^3.0.5" from the root project
npm ERR!   vue@"^3.0.5" from the root project
npm ERR!   1 more (@vueuse/motion)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 3" from @vue/composition-api@1.0.0-rc.2
npm ERR! node_modules/@vueuse/motion/node_modules/@vue/composition-api
npm ERR!   optional @vue/composition-api@"^1.0.0-rc.2" from @vueuse/motion@1.1.3
npm ERR!   node_modules/@vueuse/motion
npm ERR!     @vueuse/motion@"*" from the root project
```

I've seen that vueuse repo doesn't have peerDependencies specified, maybe that is the solution if it's compatible with Vue 2 and Vue 3?.

**Comment by Tahul** [comment] 2021-02-26 20:03
Hello @santicros ;

Thank you for your feedback, honestly this is strange because I've had multiple feedbacks from people using the package in a similar scenario, so maybe there's something wrong in your package.json ?

I'll try to remove the peerDeps as you mentioned vueuse core does not have it so it doesn't seem to be necessary.

**Comment by santicros** [comment] 2021-02-26 20:08
I think the problem is coming with npm 7. I've seen @antfu was having the same issue in vue-demi https://github.com/vueuse/vue-demi/issues/29 and it finaly deleted the  @vue/composition-api as a dependency, optional dependency or peerdependency.

I've seen it's like this in @vueuse/core and vue-demi

**Comment by Tahul** [comment] 2021-02-26 20:11
@santicros ; could you try 1.1.4 ?

I just published it.

**Comment by santicros** [comment] 2021-02-26 20:12
It's working now @Tahul !! Thanksssss ❤️

**Comment by Tahul** [comment] 2021-02-26 20:13
You're welcome @santicros ; thank you a lot for your feedback!

Have fun using it and don't forget sharing your creations with me on [Twitter](https://twitter.com/yaeeelglx).

**Comment by AMontagu** [comment] 2021-02-27 09:25
Removing peerDependencies may result on some yarn versions.

See: https://github.com/vueuse/vue-demi/issues/9

Here is a correct fix with the npm peerDepencies: https://github.com/vueuse/vue-demi/issues/37 now in the readme of vue-demi

**Comment by Tahul** [comment] 2021-02-27 12:51
@AMontagu ;

Could you give a try to 1.1.7 and tell me if everything is going okay ?

Thank you a lot for your feedback, I'm not so used to all those package managers differences yet. 🤷‍♂️

**Comment by santicros** [comment] 2021-02-27 15:27
I've checked and with npm 7 version 1.1.7 is still working great.

**Comment by AMontagu** [comment] 2021-02-27 18:20
Thank you @santicros to test it.

@Tahul I am not actually a motion user. Just see this issue referenced in vue-demi and wanted to help so can't really test this but it should work as expected for all package manager and version as it's the official way to do in the doc.
